---
jobs:
  - name: scan
    public: true
    plan:
    - get: infrastructure-repo
      trigger: true
    - task: tflint
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: wata727/tflint, tag: "latest"}
        inputs:
          - name: infrastructure-repo
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/scan.sh"]
  - name: build
    public: true
    serial_groups: [version]
    plan:
    - get: infrastructure-repo
      passed: ["scan"]
      trigger: true
    - get: version
      params: {pre: rc}
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform, tag: "light"}
        inputs:
          - name: infrastructure-repo
          - name: version
        outputs:
          - name: terraform-plan
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/build.sh", "stage"]

resources:
- name: infrastructure-repo
  type: git
  source:
    uri: git@github.com:therasec/terraform-pipeline.git
    branch: master
    private_key: ((gh-private-key))
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: git@github.com:therasec/terraform-pipeline.git
    branch: version
    file: version
    private_key: ((gh-private-key))
