---
jobs:
  - name: scan
    public: true
    plan:
    - get: infrastructure-repo
      trigger: true
    - task: tflint
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: wata727/tflint, tag: "latest"}
        inputs:
          - name: infrastructure-repo
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/scan.sh"]
  - name: build
    public: true
    serial_groups: [version]
    plan:
    - get: infrastructure-repo
      passed: ["scan"]
      trigger: true
    - get: version
      params: {pre: rc}
    - task: build
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: hashicorp/terraform, tag: "light"}
        inputs:
          - name: infrastructure-repo
          - name: version
          - name: send-email
        outputs:
          - name: terraform-plan-out
          - name: email-out
        params:
          OUTPUT_SUBJECT_FILE_NAME: generated-subject
          OUTPUT_BODY_FILE_NAME: generated-body
          OUTPUT_RECEPIENTS_FILE_NAME: generated-recepients
        run:
          path: sh
          args: ["infrastructure-repo/ci/scripts/build.sh", "stage"]
    - put: terraform-pipeline-artifacts
      params: {file: terraform-plan-out/terraform-plan-*.tgz}
    - put: version
      params: {file: version/number}
    - put: send-email
      params:
        subject: email-out/generated-subject
        body: email-out/generated-body

resources:
- name: infrastructure-repo
  type: git
  source:
    uri: ((github-uri))
    branch: master
    private_key: ((github-private-key))
- name: version
  type: semver
  source:
    driver: git
    initial_version: 0.0.1
    uri: ((github-uri))
    branch: version
    file: version
    private_key: ((github-private-key))
- name: terraform-pipeline-artifacts
  type: s3
  source:
    bucket: terraform-pipeline-rc
    regexp: terraform-plan-(.*).tgz
    access_key_id: ((s3-access-key-id))
    secret_access_key: ((s3-secret-access-key))
- name: send-email
  type: email
  source:
    smtp:
      host: {{smtp-host}}
      port: {{smtp-port}}
      anonymous: false
      username: {{smtp-username}}
      password: {{smtp-password}}
    from: {{email-from}}
    to: {{email-from}}

resource_types:
  - name: email
    type: docker-image
    source:
      repository: pcfseceng/email-resource
